name: GitHub Notifier for Teams
description: "Send gihub issues and pull requests notifications via Teams channel"
author: "Pablo Velasco"

branding:
  icon: "bell"
  color: "purple"

inputs:
  teamsSecret:
    description: 'Teams secret'
    required: true
  
runs: 
  using: "composite"

  steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Docker image
        shell: bash
        run: docker build -t github-notifier-teams .

      - name: Run Docker container
        shell: bash
        env:
          CONTEXT: "${{toJson(github.event)}}"
          TEAMS: ${{ inputs.teamsSecret }}
        run: docker run --rm -e CONTEXT -e TEAMS_SECRET github-notifier-teams